- backend/TraderX/.gitignore
- backend/TraderX/README.md
- backend/TraderX/pom.xml
- backend/TraderX/src/main/java/cmpe451/group6/Group6BackendService.java
- backend/TraderX/src/main/java/cmpe451/group6/JwtAuthServiceApp.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/configuration/SwaggerConfig.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/controller/LoginController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/controller/PasswordController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/controller/SignupController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/controller/UserController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/dto/StringResponseWrapper.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/dto/TokenWrapperDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/dto/UserDataDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/email/EmailService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/email/EmailServiceConfig.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/exception/GlobalExceptionHandlerController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/RegistrationStatus.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/User.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/security/JwtTokenFilter.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/security/JwtTokenProvider.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/security/WebSecurityConfig.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/LoginService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/PasswordService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/SignupService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/UserService.java
- Email service is now active. User has to be verify her/his email address to complete sign up process.
- Passwords can be reset by email.
More info can be found at backend/TraderX/README.md
> Backend email

- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/User.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/template/controller/TemplateController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/template/dto/TemplateItemResponseDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/template/model/TemplateItem.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/template/repository/TemplateItemRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/template/service/TemplateItemService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/trial/controller/TrialController.java
I've added a template endpoint. Try not to test it since it will not work. Its purpose is to show which project structure has to be followed when creating a new endpoint.
> Add template endpoint.

- backend/TraderX/src/main/java/cmpe451/group6/Group6BackendService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/exception/GlobalExceptionHandlerController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/security/JwtTokenFilter.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/security/JwtTokenProvider.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/HazelcastService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/PasswordService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/SignupService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/UserService.java
- backend/TraderX/src/main/resources/application.yml
- Constants are stored in application.properties
- /change endpoint is added to change password directly via token
- HazelcastService is converted to SpringService.
> Move constants to application.prop

- backend/TraderX/src/main/java/cmpe451/group6/Group6BackendService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/exception/GlobalExceptionHandlerController.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/User.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/security/JwtTokenProvider.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/HazelcastService.java
Fixes the problem of running both fronted and backend service on the same host.
> Allow cors

- backend/TraderX/src/main/java/cmpe451/group6/rest/follow/DTO/FolloweeDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/follow/controller/FollowController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/follow/model/FollowDAO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/follow/repository/FollowRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/follow/service/FollowService.java
What this PR does / why we need it:
- Some features are added wrt requirements.
- Some corrections about follow_user endpoint
> Adding features for user follow-following system

- frontend/TraderX/src/permission.js
- frontend/TraderX/src/router/index.js
- frontend/TraderX/src/views/home/index.vue
'/' path is now redirected to '/home'. And this is the first page of the website.
There are two buttons at the page: Register or Login. 
The screenshot of the home page is as below:
It would be great if you guys could take a look at it,
Thanks!
> Added home page to views.

- frontend/TraderX/src/layout/components/Navbar.vue
- frontend/TraderX/src/store/modules/user.js
- frontend/TraderX/src/utils/index.js
- frontend/TraderX/src/views/profile/components/Editprofile.vue
- frontend/TraderX/src/views/profile/components/Portfolio.vue
- frontend/TraderX/src/views/profile/components/UserCard.vue
- frontend/TraderX/src/views/profile/index.vue
I added edit profile page, also minor additions like default profile image, default portfolio template etc. Can you review it.
> Add edit profile page

- frontend/TraderX/src/views/login/index.vue
- frontend/TraderX/src/views/register/index.vue
Hey guys, 
I went over the design of registration and login pages.
I made them a little bit more harmonic with the home page. 
It would be great if you could take a look at them. The followings are the screenshots of the new design: 
Thanks!
> Frontend login/registration page design

- frontend/TraderX/src/api/search.js
- frontend/TraderX/src/components/HeaderSearch/index.vue
- frontend/TraderX/src/layout/components/Navbar.vue
- frontend/TraderX/src/permission.js
- frontend/TraderX/src/router/index.js
- frontend/TraderX/src/store/getters.js
- frontend/TraderX/src/store/modules/search.js
- frontend/TraderX/src/utils/index.js
- frontend/TraderX/src/views/search/index.vue
- frontend/TraderX/src/views/user-profile/index.vue
I implemented search user page, can you check it out?
> Frontend dev usersearch

- frontend/TraderX/src/api/user.js
- frontend/TraderX/src/permission.js
- frontend/TraderX/src/router/index.js
- frontend/TraderX/src/store/modules/user.js
- frontend/TraderX/src/views/login/index.vue
- frontend/TraderX/src/views/login/renew-password.vue
Forgot password functionality is added.
> Frontend dev forgot password

- frontend/TraderX/src/router/index.js
- frontend/TraderX/src/views/trading-equipment/components/LineChart.vue
- frontend/TraderX/src/views/trading-equipment/components/mixins/resize.js
- frontend/TraderX/src/views/trading-equipment/index.vue
Hi guys,
I added a page for trading equipments. The following is a gif for the page. 
Currently the data is being created randomly. We need to have an endpoint for receiving these weekly/monthly datas from backend. After having the endpoints prepared I will patch that into the code.
It would be great if you could take a look at this. 
**Note** : This commit was previously, mistakenly, pushed into frontend-dev branch and deleted afterwards.
Thanks in advance!
> [Frontend] Added Trading Equipments Page

- backend/TraderX/src/main/java/cmpe451/group6/Group6BackendService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/User.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/UserService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/comment/controller/CommentController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/comment/model/CommentRequestDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/comment/model/CommentResponseDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/comment/model/EquipmentComment.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/comment/repository/EquipmentCommentRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/comment/service/EquipmentCommentService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/controller/EquipmentController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/dto/Currency3rdPartyDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/dto/CurrencyHistory3rdPrtyDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/dto/EquipmentHistoryDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/dto/EquipmentResponseDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/model/Equipment.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/model/HistoricalValue.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/repository/EquipmentRepsitory.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/repository/HistoricalValueRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/service/EquipmentService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/service/EquipmentUpdateService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/follow/service/FollowService.java
- backend/TraderX/src/main/resources/application.yml
- Comment service for equipments is implemented.
- History values for equipments are moved to a separate table in order to prevent `EmptyBag`  problem caused by LAZY fetch type for collections.
> Create comment service and endpoints

- frontend/TraderX/.gitignore
- frontend/TraderX/src/api/user.js
- frontend/TraderX/src/components/CoolCard/index.vue
- frontend/TraderX/src/store/modules/user.js
- frontend/TraderX/src/views/profile/components/Editprofile.vue
- frontend/TraderX/src/views/profile/components/Portfolio.vue
- frontend/TraderX/src/views/profile/components/UserCard.vue
- frontend/TraderX/src/views/profile/index.vue
- frontend/TraderX/src/views/search/index.vue
- frontend/TraderX/src/views/user-profile/index.vue
After the endpoints that our backend supplied, I implemented the following system. For now, a user can be followed/unfollowed using search page. Normally, when we enter a user's profile, we need to see a follow/unfollow button. However, I faced with a problem with adding this functionality to user's profile page and couldn't solve it. So, currently we don't have this feature, this will be added to the system later on. This is how our system looks now:
As we can see there is a requested button in the user's own profile, this is appearing with the same reason with problem described above. After implementing this functionality, this button will disappear.
> Follow System and Portfolio Creation

- frontend/TraderX/src/views/trading-equipment/index.vue
Hi guys, 
With this PR the rest of the trading equipment (Stocks and CryptoCurrencies) are connected to backend. The look hasn't changed after the PR #193 (Current value for equipment was added to the list page in that PR).
Data of Money Currencies were already connected to backend in the PR #181 . With this the charts and the tabs of Stocks and CryptoCurrencies are also connected to backend. 
Also, regarding the latency; I filled the data array a little bit earlier comparing to the version in PR #181 like what @sadullahgultekin said but there is still a little latency, but the data gets created smoother than before. Let's decide whether the latency is a problem or not. 
It would be great if you could take a look at the changes.
Thanks in advance!
> [Frontend] Connected every trading equipment to backend in List of Equipment Page

- frontend/TraderX/src/views/trading-equipment/cryptocurrencies.vue
- frontend/TraderX/src/views/trading-equipment/money_currencies.vue
- frontend/TraderX/src/views/trading-equipment/stocks.vue
As explained in the issue #176, after a discussion with the customers, they told us that they wanted a detailed explanation about the categories that the equipment were compared in, in the radar chart.
With this PR an explanation is added to the detailed pages of the equipment. 
Also, I realized that the stability calculations were not being made correctly. I believe I fixed it now and it should work properly. 
It would be great if you guys could take a look at it. 
Thanks in advance!
> [Frontend] Fixed calculations and added explanations for Radar Chart in Detailed Pages 

- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/User.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/controller/EquipmentController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/model/Equipment.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/service/EquipmentService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/controller/PortfolioController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/dto/PortfolioEquipmentDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/dto/PortfolioResponseDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/model/Portfolio.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/repository/PortfolioRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/service/PortfolioService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/transaction/controller/TransactionController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/transaction/repository/TransactionRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/transaction/service/TransactionService.java
- A portfolio is: Grouping of financial assets such as stocks, bonds, commodities, currencies and cash equivalents, as well as their fund counterparts, including mutual, exchange-traded and closed funds.
- Considering the requirements, Portfolio System is implemented.
> Portfolio Facility

- android/TraderX/app/src/main/res/layout/activity_login.xml
- android/TraderX/app/src/main/res/layout/dialog_become_trader.xml
- android/TraderX/app/src/main/res/layout/fragment_auth_user.xml
- android/TraderX/app/src/main/res/layout/fragment_auth_user_edit.xml
- android/TraderX/app/src/main/res/layout/fragment_equipment.xml
- android/TraderX/app/src/main/res/layout/fragment_equipment_types.xml
- android/TraderX/app/src/main/res/layout/fragment_search.xml
- android/TraderX/app/src/main/res/layout/fragment_transaction.xml
- android/TraderX/app/src/main/res/layout/fragment_user.xml
- android/TraderX/app/src/main/res/layout/item_alert.xml
- android/TraderX/app/src/main/res/layout/item_comment.xml
- android/TraderX/app/src/main/res/layout/item_equipment.xml
- android/TraderX/app/src/main/res/layout/item_follow.xml
- android/TraderX/app/src/main/res/layout/item_profile.xml
- android/TraderX/app/src/main/res/layout/item_transaction.xml
- android/TraderX/app/src/main/res/layout/layout_forgot_activity.xml
- android/TraderX/app/src/main/res/values/strings.xml
Move strings from layout files to strings.xml
> move all strings to xml

- backend/TraderX/src/main/java/cmpe451/group6/authorization/model/User.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/controller/PortfolioController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/dto/PortfolioNamesDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/repository/PortfolioRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/service/PortfolioService.java
- Considering the request from front-end team, an endpoint that returns all portfolios of the requester is implemented.
Related manual testing is done.
> Portfolio(Endpoint): Get all Portfolios Functionality

- backend/TraderX/src/main/java/cmpe451/group6/Group6BackendService.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/dto/UserResponseDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/authorization/service/UserService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/repository/HistoricalValueRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/service/EquipmentUpdateService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/controller/PredictionController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/dto/ListResponseWrapper.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/dto/PredictionDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/dto/PredictionStatsDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/model/Prediction.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/repository/PredictionRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/predict/service/PredictionService.java
Prediction service has been implemented. Detailed information can be seen on api-doc/prediction.
> [Backend] Add prediction service

- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/model/Portfolio.java
- This PR aimed to fix a bug pointed out at: https://github.com/bounswe/bounswe2019group6/issues/263 , mainly fixing a problem about adding equipments to Portfolio
- Manual testing is done.
> portfolio(bug-fix): issued at #263, add enpoint

- backend/TraderX/src/main/java/cmpe451/group6/rest/equipment/repository/EquipmentRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/controller/PortfolioController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/repository/PortfolioRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/portfolio/service/PortfolioService.java
We can add multiple equipments at once now. Also return type for all equipments is updated
> Add multiple equipments to portfolio

- backend/TraderX/src/main/java/cmpe451/group6/helpers/CustomModelMapper.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/controller/ArticleController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/dto/ArticleDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/dto/ArticleInfoDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/model/Article.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/repository/ArticleRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/service/ArticleService.java
Hello backend-team, I have implemented the article controller, service, repository and all modifications related to articles have been made.
> Backend article

- frontend/TraderX/src/utils/validate.js
- frontend/TraderX/src/views/login/index.vue
- frontend/TraderX/src/views/login/renew-password.vue
- frontend/TraderX/src/views/profile/components/Editprofile.vue
- frontend/TraderX/src/views/profile/index.vue
- frontend/TraderX/src/views/register/index.vue
Hi guys,
I've added hint pop-ups to passwords fields in register, renew password, and change password forms. I didn't add it to login as we do not validate password when logging in.
Below, you can see the appearances of password hint message on different pages:
- Register:
- Renew Password
- Password change in "Edit Profile" tab:
Please comment if you notice any problem or anything you want me to change.
Thanks :)
> Password Hint

- backend/TraderX/src/main/java/cmpe451/group6/helpers/CustomModelMapper.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/controller/SearchController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/dto/ArticleSearchDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/dto/EquipmentSearchDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/dto/UserSearchDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/repository/SearchArticleRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/repository/SearchEquipmentRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/repository/SearchUserRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/search/service/SearchService.java
Search functionalities for user,equipment and article is implemented. Return types and requested parameters can be found on api.traderx.company in detail. 
* Equipment: 
1. search/equipment/byName: "params" : equipmentName, return type: Equipment
2. search/equipment/byCode: "params" : equipmentCode, return type: Equipment
* User: 
1. search/user/byName: "params" : userName, return type: User
* Article: 
1. search/article/byHeader: "params" : articleHeader return type: Article
2. search/article/byTag:  "params" : articleTag,  return type: Article
> All search functionalities for user, equipment and article implemented.

- frontend/TraderX/src/api/search.js
- frontend/TraderX/src/router/index.js
- frontend/TraderX/src/store/getters.js
- frontend/TraderX/src/store/modules/search.js
- frontend/TraderX/src/views/events/index.vue
- frontend/TraderX/src/views/profile/components/Editprofile.vue
- frontend/TraderX/src/views/search/index.vue
Hi guys,
After the backend implementation of events, I implemented the frontend part. I added new "Events" page which is shown on the left navigation bar. Also "search in events" functionality is added. Some screen shots are below. We can change our design if you wish when we meet up.
> Frontend events

- android/TraderX/app/src/main/java/com/traderx/api/response/AlertResponse.kt
- android/TraderX/app/src/main/java/com/traderx/api/response/EquipmentResponse.kt
- android/TraderX/app/src/main/java/com/traderx/db/User.kt
- android/TraderX/app/src/main/java/com/traderx/type/AlertType.kt
- android/TraderX/app/src/main/java/com/traderx/type/EquipmentType.kt
- android/TraderX/app/src/main/java/com/traderx/type/FollowingStatus.kt
- android/TraderX/app/src/main/java/com/traderx/type/Role.kt
- android/TraderX/app/src/main/java/com/traderx/type/TransactionType.kt
- android/TraderX/app/src/main/java/com/traderx/ui/alert/AlertFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/equipment/EquipmentRecyclerViewAdapter.kt
- android/TraderX/app/src/main/java/com/traderx/ui/equipment/EquipmentTypesFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/equipment/EquipmentsFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/profile/AuthUserFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/profile/UserFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/transaction/TransactionFragment.kt
- android/TraderX/app/src/main/res/navigation/mobile_navigation.xml
Since java starts to complain about the enum package name, I have to rename it to type.
> enum package renamed to type

- backend/TraderX/src/main/java/cmpe451/group6/rest/annotation/controller/AnnotationController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/annotation/dto/AnnotationDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/annotation/model/Annotation.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/annotation/repository/AnnotationRepository.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/annotation/service/AnnotationService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/model/Article.java
- Following the standards that are stated at w3c: https://www.w3.org/TR/annotation-model/ annotation facility is implemented. 
- For text annotation to a text content:
```
{
"@context": "http://www.w3.org/ns/anno.jsonld",
"id": <Id of the annotation>,
"type": "Annotation",
"creator": "https://traderx.company/user/<username>/profile",
"created": "2015-01-28T12:00:00Z",
"modified": "2015-01-29T09:00:00Z",
"body":     
{
"type": "Text",
"value": "Lorem ipsum dolor sit amet"
}
"target": {
"type": "Text",
"id": <Id of the article>,
"selector": {
"type": "TextPositionSelector", (detailed: https://www.w3.org/TR/annotation-model/#text-position-selector)
"start": 412,
"end": 795
}
}
}
```
- For text annotation to an image content:
```
{
"@context": "http://www.w3.org/ns/anno.jsonld",
"id": <Id of …
```
> Annotation Facility

- backend/TraderX/pom.xml
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/controller/ArticleController.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/dto/ArticleDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/dto/ArticleInfoDTO.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/model/Article.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/article/service/ArticleService.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/aws/AmazonClient.java
- backend/TraderX/src/main/java/cmpe451/group6/rest/aws/ImageUploadController.java
- backend/TraderX/src/main/resources/application.yml
Hello all, Image upload system for articles has been implemented. 
In order to upload images with articles.
- First you have to use **image/upload** endpoint. 
- After uploading, it returns imageUrl in response body.
- Then you can use that url while creating/editing the article as you did before.
Note that: in the **image/upload** endpoint, you should pass the image in the body as type "file". 
Detailed explanations can be found on the swagger api website.
I'm also tagging other team members to make sure that they are aware of the new image upload system. @burakyuksel0 @sadullahgultekin @irmakguzey @msdalp @barandenizkorkmaz @bwqr
> Backend image upload

- android/TraderX/app/src/main/java/com/traderx/api/request/AlertRequest.kt
- android/TraderX/app/src/main/java/com/traderx/api/response/AlertResponse.kt
- android/TraderX/app/src/main/java/com/traderx/ui/alert/AlertFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/alert/AlertRecyclerViewAdapter.kt
- android/TraderX/app/src/main/java/com/traderx/ui/portfolio/PortfolioFragment.kt
Fix updated fields on requests.
> Fix alert field update

- android/TraderX/app/src/main/java/com/traderx/api/ApiEndpoint.kt
- android/TraderX/app/src/main/java/com/traderx/api/RequestService.kt
- android/TraderX/app/src/main/java/com/traderx/api/response/AssetsResponse.kt
- android/TraderX/app/src/main/java/com/traderx/ui/profile/AssetRecyclerViewAdapter.kt
- android/TraderX/app/src/main/java/com/traderx/ui/profile/AssetsFragment.kt
- android/TraderX/app/src/main/java/com/traderx/ui/profile/AuthUserFragment.kt
- android/TraderX/app/src/main/java/com/traderx/viewmodel/AuthUserViewModel.kt
- android/TraderX/app/src/main/java/com/traderx/viewmodel/UserViewModel.kt
- android/TraderX/app/src/main/res/drawable/color_disabled.xml
- android/TraderX/app/src/main/res/layout/fragment_assets.xml
- android/TraderX/app/src/main/res/layout/fragment_auth_user.xml
- android/TraderX/app/src/main/res/layout/item_asset.xml
- android/TraderX/app/src/main/res/layout/layout_asset_modal.xml
- android/TraderX/app/src/main/res/navigation/mobile_navigation.xml
- android/TraderX/app/src/main/res/values/styles.xml
> asset page is implemented
